create table "public"."accounts" (
    "id" uuid not null,
    "connect_at" timestamp with time zone default now(),
    "image" text,
    "name" text,
    "organization_id" bigint,
    "type" text,
    "token" text
);


alter table "public"."accounts" enable row level security;

create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone,
    "account_id" uuid,
    "can_hide" boolean,
    "message" text,
    "permalink" text,
    "status" text
);


alter table "public"."comments" enable row level security;

CREATE UNIQUE INDEX accounts_pkey ON public.accounts USING btree (id);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

alter table "public"."accounts" add constraint "accounts_pkey" PRIMARY KEY using index "accounts_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."accounts" add constraint "accounts_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."accounts" validate constraint "accounts_organization_id_fkey";

alter table "public"."comments" add constraint "comments_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) not valid;

alter table "public"."comments" validate constraint "comments_account_id_fkey";